name: flutter_intro
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  email_validator: ^2.1.17
  flutter_pw_validator: ^1.6.0
  http: ^1.1.0
  get: ^4.6.6
  shared_preferences: ^2.2.1
  table_calendar: ^3.0.9
  hexcolor: ^3.0.1
  flutter_image_slideshow: ^0.1.6
  syncfusion_flutter_datepicker: ^23.1.39
  flutter_beautiful_popup: ^1.7.0
  checkbox_formfield: ^0.2.0
  email_auth: ^1.1.1
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  image_picker: ^1.0.4
  video_player: ^2.7.2
  syncfusion_flutter_calendar: ^23.1.40
  sidebarx: ^0.16.2
  data_table_2: ^2.5.8
  syncfusion_flutter_datagrid: ^23.1.40
  timeline_tile: ^2.0.0
  flutter_showcase_nullsafety: ^1.0.0
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4
  comment_box: ^0.0.18
  comment_tree: ^0.3.0
  url_launcher: ^6.1.14
  localization: ^2.1.0
  syncfusion_localizations: ^23.1.42
  syncfusion_flutter_charts: ^23.1.42
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
      - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
    - family: 'Fjalla One'
      fonts:
        - asset: fonts/Fjalla_One/FjallaOne-Regular.ttf
    - family: 'Asap'
      fonts: 
        - asset: fonts/Asap/Asap-Italic-VariableFont_wdth,wght.ttf
        - asset: fonts/Asap/Asap-VariableFont_wdth,wght.ttf
    - family: 'Open Sans'
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf
    - family: 'Proza Libre'
      fonts:
        - asset: fonts/Proza_Libre/ProzaLibre-Bold.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-BoldItalic.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-ExtraBold.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-ExtraBoldItalic.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-Italic.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-Medium.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-MediumItalic.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-Regular.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-SemiBold.ttf
        - asset: fonts/Proza_Libre/ProzaLibre-SemiBoldItalic.ttf
    - family: 'Libre Baskerville'
      fonts:
        - asset: fonts/Libre_Baskerville/LibreBaskerville-Bold.ttf
        - asset: fonts/Libre_Baskerville/LibreBaskerville-Italic.ttf
        - asset: fonts/Libre_Baskerville/LibreBaskerville-Regular.ttf
    - family: 'Raleway'
      fonts:
        - asset: fonts/Raleway/Raleway-Italic-VariableFont_wght.ttf
        - asset: fonts/Raleway/Raleway-VariableFont_wght.ttf
  uses-material-design: true
